Repository WildCodeSchool-2024-02/JS-RemoteFR-CrewDragon-P2-Team2, pull requests merged in 2024-04, with the labels that each got.

#27 init tailwind
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.jsx
  client/src/index.css
  client/src/main.jsx
  client/tailwind.config.js
Labels: REVIEWED

#28 Création Composant Footer
  client/src/App.jsx
  client/src/components/Footer.jsx
Labels: CONFLICTS RESOLVED

#31 create component Playground
  client/src/App.jsx
  client/src/components/Playground.jsx
Labels: REVIEWED

#34 Création composant Rules avec bouton fléché
  client/src/App.jsx
  client/src/components/Rules.jsx
Labels: CONFLICTS

#30 Ajout de la section Introduction
  client/src/App.jsx
  client/src/assets/images/Harrypotter.png
  client/src/assets/images/background.webp
  client/src/components/Footer.jsx
  client/src/components/Introduction.jsx
  client/src/components/Playground.jsx
  client/src/components/Rules.jsx
  client/src/index.css
  client/src/main.jsx
Labels: CONFLICTS

#36 create component CharacterSelection + map of cards
  client/src/App.jsx
  client/src/charactersSelection.css
  client/src/components/CharactersSelection.jsx
  client/src/index.css
  client/src/main.jsx
  client/tailwind.config.js
Labels: REVIEWED

#37 Customizing Tailwind
  client/index.html
  client/tailwind.config.js
Labels: CONFLICTS RESOLVED

#32 Add images in directory and apply favicon and title in head
  client/index.html
  client/src/App.jsx
  client/src/assets/favicon.png
  client/src/assets/images/HummingBird1.png
  client/src/assets/images/In the bedroom.webp
  client/src/assets/images/In the laboratory.webp
  client/src/assets/images/In the library.webp
  client/src/assets/images/In the livingroom.webp
  client/src/assets/images/In the reception room.webp
  client/src/assets/images/cube-like artifa.png
  client/src/assets/images/magic wand elegant.png
  client/src/assets/images/object crystal orb encased magic.png
  client/src/assets/images/small magic object.png
  client/src/components/.gitkeep
  client/src/components/ScoreBoard.jsx
Labels: CONFLICTS RESOLVED

#38 update style Selection Cards
  client/src/charactersSelection.css
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
Labels: REVIEWED

#45 Button spells
  client/src/App.jsx
  client/src/components/ButtonSpells.jsx
  package-lock.json
Labels: REVIEWED

#42 Ajout de la card Personnage
  client/src/components/CharacterCard.jsx
  client/src/components/Intro.jsx
  client/src/components/Playground.jsx
  client/src/index.css
Labels: REVIEWED

#49 Ajout du css dans Introduction et Rules
  client/src/components/Introduction.jsx
  client/src/components/Rules.jsx
  client/src/index.css
Labels: REVIEW REQUESTED

#52 Us31 s1 playground
  client/src/components/Playground.jsx
  client/src/components/ScoreBoard.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/playground.css
  client/tailwind.config.js
Labels: CORRECTIONS DONE, REVIEWED

#56 add modal to block play
  client/src/App.jsx
  client/src/components/ButtonSpells.jsx
  client/src/components/NavBar.jsx
  client/src/components/Playground.jsx
  client/src/playground.css
Labels: REVIEW REQUESTED

#54 Add cards in playground
  client/src/components/Playground.jsx
  client/src/playground.css
Labels: CONFLICTS RESOLVED

#55 buttons can now be disabled
  client/src/App.jsx
  client/src/components/ButtonSpells.jsx
  client/src/components/Playground.jsx
Labels: CONFLICTS RESOLVED

#60 modify css in index and playground
  client/src/components/CharacterCard.jsx
  client/src/components/Playground.jsx
  client/src/index.css
  client/src/playground.css
Labels: REVIEWED

#61 mise en place api
  client/src/App.jsx
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
Labels: REVIEWED

#68 hotfix hero section
  client/src/App.jsx
  client/src/components/Intro.jsx
  client/src/components/Introduction.jsx
  client/src/components/NavBar.jsx
  client/src/components/Rules.jsx
  client/src/index.css
Labels: REVIEWED

#69 Fix css tailwind
  client/src/App.jsx
  client/src/assets/images/bedroom.webp
  client/src/assets/images/laboratory.webp
  client/src/assets/images/library.webp
  client/src/assets/images/livingroom.webp
  client/src/assets/images/reception.webp
  client/src/charactersSelection.css
  client/src/components/CharacterCard.jsx
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
  client/src/components/Playground.jsx
  client/src/components/ScoreBoard.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/playground.css
Labels: REVIEWED

#74 Use state spells
  client/src/components/ButtonSpells.jsx
  client/src/components/NavBar.jsx
  client/src/components/Playground.jsx
Labels: REVIEWED

#75 New amandine
  client/src/components/Playground.jsx
Labels: CONFLICTS RESOLVED

#76 Create logic Playground
  client/src/components/ButtonSpells.jsx
  client/src/components/Playground.jsx
Labels: REVIEWED

#77 update esLint
  client/src/App.jsx
  client/src/assets/images/HummingBird.png
  client/src/components/CharacterCard.jsx
  client/src/components/CharacterCardPlayer.jsx
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
  client/src/components/Playground.jsx
  client/src/index.css
Labels: CHANGES REQUESTED

#78 Animations sorts
  client/src/components/CharacterCard.jsx
  client/src/components/Playground.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: REVIEW REQUESTED

#84 Set winner
  client/src/components/CharacterCardPlayer.jsx
  client/src/components/Playground.jsx
  client/src/index.css
Labels: REVIEWED

#83 modif couleurs maisons et bouton choose
  client/src/components/CharactersSelectionCard.jsx
  client/tailwind.config.js
Labels: REVIEWED

#86 hotfix spells cards
  client/src/components/Playground.jsx
  client/src/index.css
Labels: REVIEW REQUESTED, REVIEWED

#88 Blocage du boutton play tant qu'il n'y a pas de perso choisi
  client/src/App.jsx
  client/src/components/CharactersSelectionCard.jsx
  client/src/components/Playground.jsx
Labels: REVIEW REQUESTED

#87 choose char bloc
  client/src/App.jsx
  client/src/components/CharacterCard.jsx
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
  client/src/components/Playground.jsx
Labels: REVIEW REQUESTED

#91 fix anchors + local Storage
  client/src/App.jsx
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
  client/src/components/Introduction.jsx
  client/src/components/Playground.jsx
  client/src/components/ScoreBoard.jsx
Labels: REVIEW REQUESTED

#93 readme
  README.md
Labels: REVIEWED

#96 fix localstorage
  client/src/components/Playground.jsx
  client/src/components/ScoreBoard.jsx
  client/src/index.css
Labels: REVIEW REQUESTED

#102 Hotfix playground's responsive
  client/src/components/ButtonSpells.jsx
  client/src/components/CharacterCardPlayer.jsx
  client/src/components/CharactersSelection.jsx
  client/src/components/Playground.jsx
  client/src/index.css
Labels: REVIEW REQUESTED

#108 Ajout Pied de page pour remonter
  client/src/components/Footer.jsx
  client/src/index.css
Labels: REVIEW REQUESTED

#109 Ajout Css Curseur
  client/src/App.jsx
  client/src/components/Introduction.jsx
  client/src/index.css
Labels: REVIEWED

#106 hotfix responsive character selection
  client/src/components/CharactersSelection.jsx
  client/src/components/CharactersSelectionCard.jsx
  client/src/components/Playground.jsx
  client/src/components/ScoreBoard.jsx
  client/src/index.css
Labels: REVIEWED

#107 hotfix scoreboard
  client/src/components/Playground.jsx
  client/src/components/ScoreBoard.jsx
Labels: CONFLICTS RESOLVED

#110 Bouton musique
  client/src/App.jsx
  client/src/components/SoundButton.jsx
Labels: CONFLICTS RESOLVED, REVIEWED

#111 Effets sorts
  client/package.json
  client/src/App.jsx
  client/src/assets/audio/confringo.mp3
  client/src/assets/audio/magical-spell-cast-190272.mp3
  client/src/assets/audio/protego-105518.mp3
  client/src/assets/audio/protego.mp3
  client/src/assets/audio/slugulus.mp3
  client/src/assets/audio/stupefix.mp3
  client/src/components/Playground.jsx
Labels: CONFLICTS, REVIEW REQUESTED
